# Implements FR4: Service
apiVersion: v1
kind: Service
metadata:
  name: learnflow-docs
  labels:
    app: learnflow-docs
    component: documentation
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: http
    protocol: TCP
    name: http
  selector:
    app: learnflow-docs
